version: '3.8'

services:
  web:
    container_name: infoDock-v2.0
    image: willmo103/note-server:latest
    working_dir: /src
    volumes:
      - ./uploads:/src/uploads
      - ./db-data:/src/instance/notes.db
    ports:
     - "4202:4202"
    environment:
       - SECRET_KEY=${SECRET_KEY}
       - DATABASE_URL_POSTGRES=${DATABASE_URL_POSTGRES}
       - DATABASE_URL_SQLITE=${DATABASE_URL_SQLITE}
       - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
       - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
       - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
       - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    env_file:
      - .env

volumes:
  uploads: {}
  db-data: {}

