version: '3.8'

services:
  web:
    container_name: note-server-container
    image: willmo103/note-server:latest
    working_dir: /src
    ports:
      - "4202:4202"
    environment:
      - DATABASE_URL=sqlite:///notes.db
    volumes:
      - db-data:/data
    command: flask run --host=0.0.0.0 --port=4202
    restart: always
    tty: true
    stdin_open: true

volumes:
  db-data:
