version: "3.8"

services:
  web:
    container_name: infoDock-api
    build: . # image: willmo103/boarddock-api:latest
    working_dir: /src
    volumes:
      - ./uploads:/src/uploads
    ports:
      - "5000:5000" # 4203:4203
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL_POSTGRES=${DATABASE_URL_POSTGRES}
      - DATABASE_URL_SQLITE=${DATABASE_URL_SQLITE}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_ECHO=${SQLALCHEMY_ECHO}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    env_file:
      - .env
    tty: true
    restart: always

volumes:
  uploads: {}
